"""Error codes and the error envelope (§20, docs/api.md).

Every code here must appear in the registry in docs/api.md and vice versa; a test enforces it.
"""

from __future__ import annotations

from enum import StrEnum
from typing import Any


class ErrorCode(StrEnum):
    # General
    VALIDATION_ERROR = "VALIDATION_ERROR"
    NOT_FOUND = "NOT_FOUND"
    METHOD_NOT_ALLOWED = "METHOD_NOT_ALLOWED"
    MALFORMED_REQUEST = "MALFORMED_REQUEST"
    RATE_LIMITED = "RATE_LIMITED"
    IDEMPOTENCY_KEY_REQUIRED = "IDEMPOTENCY_KEY_REQUIRED"
    IDEMPOTENCY_KEY_REUSED = "IDEMPOTENCY_KEY_REUSED"
    CONFLICT = "CONFLICT"
    INTERNAL_ERROR = "INTERNAL_ERROR"
    SERVICE_UNAVAILABLE = "SERVICE_UNAVAILABLE"
    # Auth
    AUTH_REQUIRED = "AUTH_REQUIRED"
    AUTH_INVALID_CREDENTIALS = "AUTH_INVALID_CREDENTIALS"
    AUTH_TOKEN_EXPIRED = "AUTH_TOKEN_EXPIRED"
    AUTH_REFRESH_REUSED = "AUTH_REFRESH_REUSED"
    AUTH_HANDOFF_INVALID = "AUTH_HANDOFF_INVALID"
    AUTH_TOTP_REQUIRED = "AUTH_TOTP_REQUIRED"
    API_CLIENT_REVOKED = "API_CLIENT_REVOKED"
    SCOPE_MISSING = "SCOPE_MISSING"
    PERMISSION_DENIED = "PERMISSION_DENIED"
    MAKER_CHECKER_SAME_ACTOR = "MAKER_CHECKER_SAME_ACTOR"
    # Events
    SIGNATURE_INVALID = "SIGNATURE_INVALID"
    SIGNATURE_TIMESTAMP_STALE = "SIGNATURE_TIMESTAMP_STALE"
    EVENT_ID_CONFLICT = "EVENT_ID_CONFLICT"
    EVENT_TYPE_UNSUPPORTED = "EVENT_TYPE_UNSUPPORTED"
    AMOUNT_INCONSISTENT = "AMOUNT_INCONSISTENT"
    CURRENCY_NOT_ENABLED = "CURRENCY_NOT_ENABLED"
    BUSINESS_KEY_CONFLICT = "BUSINESS_KEY_CONFLICT"
    EVENT_NOT_REPLAYABLE = "EVENT_NOT_REPLAYABLE"
    # Referrals and attribution
    REFERRAL_CODE_INVALID = "REFERRAL_CODE_INVALID"
    REFERRAL_CODE_REQUIRED = "REFERRAL_CODE_REQUIRED"
    REFERRAL_CODE_TAKEN = "REFERRAL_CODE_TAKEN"
    REFERRAL_CODE_FORBIDDEN = "REFERRAL_CODE_FORBIDDEN"
    ATTRIBUTION_TOKEN_INVALID = "ATTRIBUTION_TOKEN_INVALID"
    ATTRIBUTION_TOKEN_EXPIRED = "ATTRIBUTION_TOKEN_EXPIRED"
    ATTRIBUTION_NOT_NEW_ACCOUNT = "ATTRIBUTION_NOT_NEW_ACCOUNT"
    ATTRIBUTION_TIMESTAMP_INVALID = "ATTRIBUTION_TIMESTAMP_INVALID"
    ATTRIBUTION_LOCKED = "ATTRIBUTION_LOCKED"
    SELF_REFERRAL = "SELF_REFERRAL"
    REFERRER_BLOCKED = "REFERRER_BLOCKED"
    # Commissions and rules
    COMMISSION_RULE_TIE = "COMMISSION_RULE_TIE"
    COMMISSION_RULE_INVALID = "COMMISSION_RULE_INVALID"
    COMMISSION_STATE_INVALID = "COMMISSION_STATE_INVALID"
    # Ledger, credits, payouts
    CREDIT_ACCOUNT_NOT_LINKED = "CREDIT_ACCOUNT_NOT_LINKED"
    CREDIT_CROSS_PRODUCT_DISABLED = "CREDIT_CROSS_PRODUCT_DISABLED"
    RESERVATION_ALREADY_CAPTURED = "RESERVATION_ALREADY_CAPTURED"
    RESERVATION_ALREADY_RELEASED = "RESERVATION_ALREADY_RELEASED"
    CREDIT_REFUND_EXCEEDS_CAPTURED = "CREDIT_REFUND_EXCEEDS_CAPTURED"
    INSUFFICIENT_BALANCE = "INSUFFICIENT_BALANCE"
    BALANCE_NEGATIVE = "BALANCE_NEGATIVE"
    PAYOUT_NOT_ELIGIBLE = "PAYOUT_NOT_ELIGIBLE"
    PAYOUT_STATE_INVALID = "PAYOUT_STATE_INVALID"
    LEDGER_UNBALANCED = "LEDGER_UNBALANCED"


HTTP_STATUS: dict[ErrorCode, int] = {
    ErrorCode.VALIDATION_ERROR: 422,
    ErrorCode.NOT_FOUND: 404,
    ErrorCode.METHOD_NOT_ALLOWED: 405,
    ErrorCode.MALFORMED_REQUEST: 400,
    ErrorCode.RATE_LIMITED: 429,
    ErrorCode.IDEMPOTENCY_KEY_REQUIRED: 400,
    ErrorCode.IDEMPOTENCY_KEY_REUSED: 409,
    ErrorCode.CONFLICT: 409,
    ErrorCode.INTERNAL_ERROR: 500,
    ErrorCode.SERVICE_UNAVAILABLE: 503,
    ErrorCode.AUTH_REQUIRED: 401,
    ErrorCode.AUTH_INVALID_CREDENTIALS: 401,
    ErrorCode.AUTH_TOKEN_EXPIRED: 401,
    ErrorCode.AUTH_REFRESH_REUSED: 401,
    ErrorCode.AUTH_HANDOFF_INVALID: 401,
    ErrorCode.AUTH_TOTP_REQUIRED: 401,
    ErrorCode.API_CLIENT_REVOKED: 401,
    ErrorCode.SCOPE_MISSING: 403,
    ErrorCode.PERMISSION_DENIED: 403,
    ErrorCode.MAKER_CHECKER_SAME_ACTOR: 403,
    ErrorCode.SIGNATURE_INVALID: 401,
    ErrorCode.SIGNATURE_TIMESTAMP_STALE: 401,
    ErrorCode.EVENT_ID_CONFLICT: 409,
    ErrorCode.EVENT_TYPE_UNSUPPORTED: 422,
    ErrorCode.AMOUNT_INCONSISTENT: 422,
    ErrorCode.CURRENCY_NOT_ENABLED: 422,
    ErrorCode.BUSINESS_KEY_CONFLICT: 409,
    ErrorCode.EVENT_NOT_REPLAYABLE: 409,
    ErrorCode.REFERRAL_CODE_INVALID: 422,
    ErrorCode.REFERRAL_CODE_REQUIRED: 422,
    ErrorCode.REFERRAL_CODE_TAKEN: 409,
    ErrorCode.REFERRAL_CODE_FORBIDDEN: 422,
    ErrorCode.ATTRIBUTION_TOKEN_INVALID: 422,
    ErrorCode.ATTRIBUTION_TOKEN_EXPIRED: 422,
    ErrorCode.ATTRIBUTION_NOT_NEW_ACCOUNT: 422,
    ErrorCode.ATTRIBUTION_TIMESTAMP_INVALID: 422,
    ErrorCode.ATTRIBUTION_LOCKED: 409,
    ErrorCode.SELF_REFERRAL: 422,
    ErrorCode.REFERRER_BLOCKED: 422,
    ErrorCode.COMMISSION_RULE_TIE: 409,
    ErrorCode.COMMISSION_RULE_INVALID: 422,
    ErrorCode.COMMISSION_STATE_INVALID: 409,
    ErrorCode.CREDIT_ACCOUNT_NOT_LINKED: 404,
    ErrorCode.CREDIT_CROSS_PRODUCT_DISABLED: 422,
    ErrorCode.RESERVATION_ALREADY_CAPTURED: 409,
    ErrorCode.RESERVATION_ALREADY_RELEASED: 409,
    ErrorCode.CREDIT_REFUND_EXCEEDS_CAPTURED: 422,
    ErrorCode.INSUFFICIENT_BALANCE: 422,
    ErrorCode.BALANCE_NEGATIVE: 422,
    ErrorCode.PAYOUT_NOT_ELIGIBLE: 422,
    ErrorCode.PAYOUT_STATE_INVALID: 409,
    ErrorCode.LEDGER_UNBALANCED: 500,
}


class PlatformError(Exception):
    """A business or request error with a stable code. Raised by services, rendered by the API."""

    def __init__(
        self,
        code: ErrorCode,
        message: str | None = None,
        *,
        details: dict[str, Any] | None = None,
    ) -> None:
        self.code = code
        self.message = message or code.replace("_", " ").capitalize()
        self.details = details or {}
        super().__init__(f"{code}: {self.message}")

    @property
    def http_status(self) -> int:
        return HTTP_STATUS[self.code]


def error_body(
    code: ErrorCode, message: str, request_id: str, details: dict[str, Any] | None = None
) -> dict[str, Any]:
    return {
        "success": False,
        "error": {
            "code": str(code),
            "message": message,
            "request_id": request_id,
            "details": details or {},
        },
    }
